# --- Performance --------------------------------------------------------------

# Hardware Acceleration
--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-zero-copy
--enable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoEncoder,CanvasOopRasterization,VaapiIgnoreDriverChecks,UseMultiPlaneFormatForHardwareVideo,ExtensionsMenuAccessControl,OriginKeyedProcessesByDefault
--ozone-platform-hint=auto

--disable-smooth-scrolling
--enable-parallel-downloading

# --- Security -----------------------------------------------------------------

--enable-webrtc-hide-local-ips-with-mdns
--test-third-party-cookie-phaseout
